(setq-default tab-width 2)
(set-frame-font "Liberation Mono-13")
(setq utf-translate-cjk-mode nil) ; disable CJK coding/encoding (Chinese/Japanese/Korean characters)
(set-language-environment 'utf-8)
(setq locale-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
(setq rsense-home "/usr/lib/rsense-0.3")
(add-to-list 'load-path (concat rsense-home "/etc"))
(require 'rsense)
(add-to-list 'load-path "~/.emacs.d/vendor")
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/vendor/ac-dict")
(ac-config-default)
(ac-set-trigger-key "TAB")
(textmate-mode)
(global-linum-mode)
(load-file "~/.emacs.d/vendor/cedet-1.0/common/cedet.el")
(add-to-list 'load-path "~/.emacs.d/vendor/ruby-debug-extra/emacs")
(require 'rdebug)
(setq rdebug-short-key-mode t)
(setq stack-trace-on-error t)
(add-to-list 'load-path "~/.emacs.d/vendor/ecb-2.40")
(require 'ecb)
(require 'ecb-autoloads)
(ecb-activate)
(ecb-byte-compile)
(global-set-key [f9] 'gud-step)
(global-set-key [f10] 'gud-next)
(global-set-key [f11] 'gud-cont)
(global-set-key "\C-c\C-d" 'rdebug)
;http://lists.gnu.org/archive/html/help-gnu-emacs/2011-09/msg00192.html
;TODO:  configure el-get to grab all requirements so I can place git-ignore on the el-get directories.
