(setq-default tab-width 2)
(set-frame-font "Liberation Mono-13")
(setq utf-translate-cjk-mode nil) ; disable CJK coding/encoding (Chinese/Japanese/Korean characters)
(set-language-environment 'utf-8)
(setq locale-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
(setq rsense-home "/usr/lib/rsense-0.3")
(add-to-list 'load-path (concat rsense-home "/etc"))
(require 'rsense)
(add-to-list 'load-path "~/.emacs.d/vendor")
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/vendor/ac-dict")
(ac-config-default)
(ac-set-trigger-key "TAB")
(global-auto-complete-mode t)
(textmate-mode)
(global-linum-mode)
(load-file "~/.emacs.d/vendor/cedet-1.0/common/cedet.el")
(add-to-list 'load-path "~/.emacs.d/vendor/ruby-debug-extra-0.10.4/emacs")
(require 'rdebug)
(setq rdebug-short-key-mode t)
(setq stack-trace-on-error t)  ; get rid of stack trace message. allows ecb to work.
(add-to-list 'load-path "~/.emacs.d/vendor/ecb-2.40")
(require 'ecb)
(require 'ecb-autoloads)
(setq ecb-tip-of-the-day nil)
;(setq ecb-tree-buffer-style 'ascii-guides)
(setq my-projects '("~/Projects/crushpath" "~/Projects/localredhead"))
(setq tags-table-list my-projects)
(setq ecb-source-path my-projects)
(ecb-byte-compile)
(ecb-activate)
(global-set-key "\C-c\C-d" 'rdebug)
(setq confirm-kill-emacs 'yes-or-no-p)
(setq inhibit-startup-screen t)
(setq initial-scratch-message nil)
;; Default directory
(setq default-directory "~/Projects/")
;; Navigate between emacs window panes.
(global-set-key (kbd "S-<up>") 'windmove-up)
(global-set-key (kbd "S-<down>") 'windmove-down)
(global-set-key (kbd "S-<right>") 'windmove-right)
(global-set-key (kbd "S-<left>") 'windmove-left)
(kill-buffer "*scratch*")
(kill-buffer "*Messages*")
(kill-buffer "*Compile-Log*")
;I find it very annoying to press Alt+x so I am mapping it to Shift<space> as well.
(global-set-key (kbd "C-SPC") 'execute-extended-command)
;http://lists.gnu.org/archive/html/help-gnu-emacs/2011-09/msg00192.html
;TODO:  configure el-get to grab all requirements so I can place git-ignore on the el-get directories.
